/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"
// biome-ignore lint/suspicious/noExplicitAny: autogenerated file
export const Index: Record<string, any> = {
  "index": {
    name: "index",
    type: "registry:style",
    registryDependencies: ["utils"],
    files: [],
    component: null,
  },
  "style": {
    name: "style",
    type: "registry:style",
    registryDependencies: ["utils"],
    files: [],
    component: null,
  },
  "button": {
    name: "button",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/new-york-v4/ui/button.tsx",
      type: "registry:ui"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/ui/button.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "footer-01": {
    name: "footer-01",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/new-york-v4/ui/footer-01.tsx",
      type: "registry:ui"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/ui/footer-01.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "button-demo": {
    name: "button-demo",
    type: "registry:example",
    registryDependencies: ["button"],
    files: [{
      path: "src/registry/new-york-v4/examples/button-demo.tsx",
      type: "registry:example"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/button-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "footer-01-demo": {
    name: "footer-01-demo",
    type: "registry:example",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/new-york-v4/examples/footer-01-demo.tsx",
      type: "registry:example"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/footer-01-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  }